### ISSUE TITLE
Not able to show image in body

### ISSUE THREAD

**Issue by Oneappletech** [pvsvamsi/SystemAlertWindow#1]
Not able to show image inside header,body and footer

**Comment by pvsvamsi** [comment]
Currently it's not supported

**Comment by theifedayo** [comment]
is there support for image now

**Comment by minibu2020** [comment]
Seeking for answers for this too. Is there a way we can have some Flutter core widgets in there?

**Comment by pvsvamsi** [comment]
It's supported in the latest release v2.0.0
