### ISSUE TITLE
Support for Native Platform Dialogs

### ISSUE THREAD

**Issue by imaduddinmd** [pvsvamsi/SystemAlertWindow#103]
First of all, thanks for the plugin.

I have been using this plugin to display alarm notifications, and it works very well.

It would be amazing if there is an option for a native platform-like dialogue similar to this [flutter_platform_alert](https://pub.dev/packages/flutter_platform_alert) package that could be called from alarm notifications. This would add more customisation for this plugin as I felt there aren't enough styling options in the current version.

**Comment by pvsvamsi** [comment]
It's supported in the latest release v2.0.0
