### ISSUE TITLE
IOS Running

### ISSUE THREAD

**Issue by melshenawyarabapps** [pvsvamsi/SystemAlertWindow#108]
This appear while running on IOS
MissingPluginException(No implementation found for method requestPermissions on channel in.jvapps.system_alert_window)

**Comment by anderlopz** [comment]
@melshenawyarabapps did u find any solution to this issue?

**Comment by melshenawyarabapps** [comment]
No , but I think overlay does not supported on IOS
I found another solution to use overlay on IOS
I use Picture in Picture

**Comment by melshenawyarabapps** [comment]
IOS does not support overlay

**Comment by ozhankucuk** [comment]
> No , but I think overlay does not supported on IOS I found another solution to use overlay on IOS I use Picture in Picture

can you explain your solution? Please share example.
