### ISSUE TITLE
App in background/kill state, not getting how to use it.

### ISSUE THREAD

**Issue by AvinashKahar** [pvsvamsi/SystemAlertWindow#109]
Already refer your Documents & ReadMe, still not able to call/show in background state.

My Requirement : 
Show incoming firebase push notification in dialog.

1. Perfectly working in foreground state, but required help in background/kill state.
2. Using firebase for push notification, how to manage and communicate via isolate and show that notification
3.  Required to open app particular screen or button interaction to cancel/close/accept input from user

**Comment by Psquare-0** [comment]
Hi @AvinashKahar, I am having the exact same requirement. I am able to show this system alert when the app is in background using isolate but not able to show it when the app is killed.
If you can share the respective piece of code maybe i can help. Also, please let me know if you find any solution for when the app is killed.

**Comment by pvsvamsi** [comment]
App in background - Use isolates.
App killed - That's not part of this package's scope.
