### ISSUE TITLE
Call back not registered 

### ISSUE THREAD

**Issue by rajatjain2802** [pvsvamsi/SystemAlertWindow#11]
buttons clicks are not working , it said "toRawHandle" call on null , in your clone project callbacks are working but in my project its not working ..
 @override
  void initState() {
    super.initState();
    _initPlatformState();
    _checkPermissions();
    SystemAlertWindow.registerOnClickListener((tag) {
      switch (tag) {
        case "simple_button":
          SystemAlertWindow.closeSystemWindow();
          break;
        case "updated_simple_button":
          SystemAlertWindow.closeSystemWindow();
          break;
        case "focus_button":
          print("Focus button has been called");
          break;
        default:
          print("OnClick event of $tag");
      }
    });
}

this is the code.
and for show overlay window I create separate class  . Like this:
CallDialog().showOverlayWindow();

**Comment by rajatjain2802** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
E/flutter (29958): Receiver: null
E/flutter (29958): Tried calling: toRawHandle()
E/flutter (29958): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (29958): #1      SystemAlertWindow.registerOnClickListener (package:system_alert_window/system_alert_window.dart:65:62)
E/flutter (29958): #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
E/flutter (29958): #3      SystemAlertWindow.registerOnClickListener (package:system_alert_window/system_alert_window.dart:44:46)
E/flutter (29958): #4      MyAppState.getOverlayWindow.<anonymous closure> (package:connx/main.dart:207:31)
E/flutter (29958): #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
E/flutter (29958): #6      MyAppState.getOverlayWindow.<anonymous closure> (package:connx/main.dart:206:42)
E/flutter (29958): #7      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter (29958): #8      _rootRun (dart:async/zone.dart:1122:38)
E/flutter (29958): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (29958): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (29958): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (29958): #12     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (29958): #13     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (29958): #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (29958): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (29958): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (29958): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (29958): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


this error is coming

**Comment by pvsvamsi** [comment]
@rajatjain2802 You are registering a scoped function as the callback function for the button click events.
As mentioned in the [Readme](https://github.com/pvsvamsi/SystemAlertWindow#register-for-onclick-events-button-click),
You have to move the callback function to the parent scope.
