### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by GravityC** [pvsvamsi/SystemAlertWindow#114]
**This error occurs when I add this plugin，what should i do**

* What went wrong:
A problem occurred configuring project ':system_alert_window'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.

**Comment by GravityC** [comment]
![Uploading 微信图片_20240127201220.png…]()

**Comment by GravityC** [comment]
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Warning: The plugin system_alert_window requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':system_alert_window'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by pvsvamsi** [comment]
You need to update your compile sdk to 34
