### ISSUE TITLE
bug when running app

### ISSUE THREAD

**Issue by alhlal209** [pvsvamsi/SystemAlertWindow#15]
Note: C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\system_alert_window-0.2.2+2\android\src\main\java\in\jvapps\system_alert_window\services\WindowService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\system_alert_window-0.2.2+2\android\src\main\java\in\jvapps\system_alert_window\SystemAlertWindowPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: E:\flutter apps\toast_flutter\android\app\src\main\kotlin\com\example\toastflutter\Application.kt: (16, 48): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected
e: E:\flutter apps\toast_flutter\android\app\src\main\kotlin\com\example\toastflutter\MainActivity.kt: (10, 48): Type mismatch: inferred type is MainActivity but FlutterEngine was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 39s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pvsvamsi** [comment]
You have to provide Application class equivalent for kotlin. Please google 'flutter plugin register kotlin' for further help.

**Comment by pvsvamsi** [comment]
@alhlal209 I have updated the readme file. Please see the application class section of it.
