### ISSUE TITLE
How to close System alert window when app gets destroyed

### ISSUE THREAD

**Issue by merlinko637** [pvsvamsi/SystemAlertWindow#16]
Hello, in my app, what i want to achieve is to close the currently opened SystemAlertWindow when app gets destroyed. 

I tried it through AppLifecycleState.detached but this callback is not firing in my case. 

Then I tried, in Application.kt, to add onDestroy() and call some method on method channel, so it fires and event in flutter where I would call SystemAlertWindow.closeSystemWindow(), but that didnt work, because the widget was already dead at that moment.

Im guessing the best solution would be to call it directly in onDestroy in Application.kt, but I have absolutely no idea, what method should I invoke and how. Can you somehow help me with this? :) thanks in advance

**Comment by pvsvamsi** [comment]
What are the scenarios of app getting destroyed?
Flutter app usually distorts the displaying page, rather than crashing the whole app. Your best bet is to handle things through lifecyle state.

Coming to kotlin, I have no idea

**Comment by merlinko637** [comment]
When user quits the app in the "open apps menu" (by tapping the rectangle) on android, lifecycleEvent is not called. Only onDestroy in kotlin is called, but I have no idea how to close system alert window from kotlin :/

**Comment by pvsvamsi** [comment]
This plugin is designed to work from background (i.e, independent of the app being running or not). Can you give me your use case, why you want to close when the app is closed?
