### ISSUE TITLE
Being able to drag the window even if it is resized to small rectangle

### ISSUE THREAD

**Issue by merlinko637** [pvsvamsi/SystemAlertWindow#17]
Currently the window is draggable only if the width is not set. In my project, I use this package as a small icon badge to be able to get into app quickly when the app is minimized. 

Desired behavior would be, so that user can drag this icon badge just like messenger chat heads.

Is it somehow possible to fix / implement this functionality? 

Thanks in advance :)

**Comment by pvsvamsi** [comment]
The reason for width dependency on movement is due to the reason that this package only allows vertical movement. However, you are free to implement the support for horizontal movement and raise a PR to dev branch

**Comment by merlinko637** [comment]
@pvsvamsi but current behavior is, that when the width is set and the window is moved for example to the left of the screen, also vertical movement doesnt work :/

**Comment by pvsvamsi** [comment]
Fix has been release. Upgraded the plugin to 0.3.2
