### ISSUE TITLE
SystemAlertWindow.closeSystemWindow(); is not working from Alart window

### ISSUE THREAD

**Issue by imSaharukh** [pvsvamsi/SystemAlertWindow#19]
E/flutter (24122): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method closeSystemWindow on channel in.jvapps.system_alert_window)

E/flutter (24122): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
E/flutter (24122): <asynchronous suspension>
E/flutter (24122): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
E/flutter (24122): #2      SystemAlertWindow.closeSystemWindow 
package:system_alert_window/system_alert_window.dart:114
E/flutter (24122): #3      callBack 
package:native_code/screens/overlay.dart:323
E/flutter (24122): #4      callbackDispatcher.<anonymous closure> 
package:system_alert_window/system_alert_window.dart:136
E/flutter (24122): #5      MethodChannel._handleAsMethodCall 
package:flutter/…/services/platform_channel.dart:409
E/flutter (24122): #6      MethodChannel.setMethodCallHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:377
E/flutter (24122): #7      _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:258
E/flutter (24122): #8      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:306:15)
E/flutter (24122): #9      _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (24122): #10     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (24122): #11     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (24122): #12     _invoke3  (dart:ui/hooks.dart:305:10)
E/flutter (24122): #13     _dispatchPlatformMessage  (dart:ui/hooks.dart:180:5)
E/flutter (24122):

**Comment by rafay-tariq** [comment]
i also received this error. have you resolved this or not ?

**Comment by Mohammad-ezzidden** [comment]
have you made the application class ?

**Comment by imSaharukh** [comment]
NO

**Comment by rafay-tariq** [comment]
> have you made the application class ?

not. please tell me how to do this in Flutter.

**Comment by pvsvamsi** [comment]
Application class is required for this plugin.

Application class should be created under Android folder, which is provided in the example directory as well

**Comment by imSaharukh** [comment]
@pvsvamsi I have created the application class

**Comment by rafay-tariq** [comment]
@imSaharukh no works fine ?

**Comment by imSaharukh** [comment]
no still not working

**Comment by rafay-tariq** [comment]
sad :(

**Comment by Mohammad-ezzidden** [comment]
[https://github.com/pvsvamsi/SystemAlertWindow/issues/20#issuecomment-643670049](url)

**Comment by pvsvamsi** [comment]
@imSaharukh @rafay-tariq I have updated the readme file. Please see the application class section of it.
