### ISSUE TITLE
is it possible to customize ?

### ISSUE THREAD

**Issue by belgarad** [pvsvamsi/SystemAlertWindow#2]
first of all thanks for plugging.

is it possible to customize system alert window. i dont need hearder or body. all i want is simply button. nothing else. but some how i can not do that.

**Comment by pvsvamsi** [comment]
Support is added in 0.1.4+6
Use header for button only option.
Example :

```
SystemWindowHeader header = SystemWindowHeader(
          button: SystemWindowButton(text: SystemWindowText(text: "Some button", fontSize: 10, textColor: Colors.black45), tag: "personal_btn"),
          buttonPosition: ButtonPosition.TRAILING);

SystemAlertWindow.showSystemWindow(
          height: 50, 
          width: 90, 
          header: header, 
          margin: SystemWindowMargin(left: 8, right: 8, top: 200, bottom: 0), 
         gravity: SystemWindowGravity.CENTER);
```

**Comment by Pratiknarola** [comment]
can you please tell me how to setup onPressed event for this button?

**Comment by pvsvamsi** [comment]
@Pratiknarola Please refer to the updated Readme or clone the example folder and explore the code

**Comment by Pratiknarola** [comment]
@pvsvamsi  thanks
