### ISSUE TITLE
There are errors on Application.java

### ISSUE THREAD

**Issue by KwangryeolPark** [pvsvamsi/SystemAlertWindow#20]
package com.example.covid19route;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;
public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {

    @Override
    public void onCreate() {
        super.onCreate();
        //This is required as we are using background channel for dispatching click events
        SystemAlertWindowPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry pluginRegistry) {
        GeneratedPluginRegistrant.registerWith(pluginRegistry);
    }

}

Here is my Application.java code in kotlin Folder

Android Studio say me that "cannot resolve symbol SystemAlertWindowPlugin" and "registerWith (io.flutter.embedding.engine.FlutterEngine) in GeneratedPluginRegistrant cannot be applied to (io.flutter.plugin.common.PluginRegistry))"

What is the main problem and what should I do?

**Comment by Mohammad-ezzidden** [comment]
put this instead of the registerWith function:
 override fun registerWith(registry: PluginRegistry) {
        SystemAlertWindowPlugin.registerWith(registry.registrarFor("in.jvapps.system_alert_window"));
    }

**Comment by pvsvamsi** [comment]
@Mohammad-ezzidden Can you give application class equivalent for kotlin? Looks like many users are preferring kotlin over java

**Comment by Mohammad-ezzidden** [comment]
@pvsvamsi  Here it is.
`
package {YOUR PACKAGE NAME HERE ***};

import `in`.jvapps.system_alert_window.SystemAlertWindowPlugin
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback


class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        SystemAlertWindowPlugin.setPluginRegistrant(this)
            }

   override fun registerWith(registry: PluginRegistry) {
      SystemAlertWindowPlugin.registerWith(registry.registrarFor("in.jvapps.system_alert_window"));
   }
}`

**Comment by pvsvamsi** [comment]
@KwangryeolPark I have updated the readme file. Please see the application class section of it.
