### ISSUE TITLE
Draw Over Other App not work Android 10

### ISSUE THREAD

**Issue by ronaldoasilva** [pvsvamsi/SystemAlertWindow#22]
Thanks for the work :)

Version system_alert_window: ^0.1.5+1

Draw Over Other App not work in Android 10.

Do you have any fix? Thanks.

![image](https://user-images.githubusercontent.com/14168419/85859625-d6cc2500-b793-11ea-9801-8cf8d6893c90.png)

**Comment by michael-ottink** [comment]
I have android 10 as well and it is working as expected. How did you implement it?

**Comment by pvsvamsi** [comment]
@ronaldoasilva Update the plugin to latest version or clone the example repository run it and share the results

**Comment by ronaldoasilva** [comment]
Update version system_alert_window: 0.2.0 it worked now, thanks guys :)
