### ISSUE TITLE
Is there any way to navigate back to the app from the system alert window

### ISSUE THREAD

**Issue by michael-ottink** [pvsvamsi/SystemAlertWindow#25]
Hey,

I have the system alert window. And I noticed it is using the android bubble api. And I know that the Messenger app from facebook can resume or start an app when the user clicks on the bubble. But there is absolutely nothing I can find about how they do this.

Would you by chance happen to have any idea. I have been searching for days and I don't know where else to go.

**Comment by pvsvamsi** [comment]
Quick google search returned [this](https://stackoverflow.com/a/55776575)

Closing this, as it is outside the scope of this plugin

**Comment by dutch-game-studio** [comment]
Thanks, I think the real problem was that I could not call a plugin from inside the callback because it would throw an error. Probably because you can't call another method channel from a isolate. 

I am going to try the other answer with the IsolateManager to see if it can work.
