### ISSUE TITLE
Is there any way to display an icon in the system window?

### ISSUE THREAD

**Issue by duck-dev-go** [pvsvamsi/SystemAlertWindow#26]
Is there any way to display an icon in the system window? I only see buttons and text is that correct? What would I have to do to display a or image?

**Comment by pvsvamsi** [comment]
As of 0.3.1, There is no support for icons/images in this package. I'm open for PRs with that support.

**Comment by aleeshaford** [comment]
i am also interested in displaying images in the overlay

**Comment by pvsvamsi** [comment]
It's supported in the latest release v2.0.0
