### ISSUE TITLE
How can I send a message from the callback to the app?

### ISSUE THREAD

**Issue by michael-ottink** [pvsvamsi/SystemAlertWindow#27]
@pvsvamsi  How can I send a message from the callback to the app? You told me I should use the IsolateManager but I can't seem to find that class in the flutter docs. And I can't find an isolate being spawned anywhere. I more info about this would also be good to have in the SystemAlertWindow docs.

```
  static Future<void> systemOverlayOnClickListner(String value) async {
    if (value == 'button_app_to_foreground') {
      await SystemAlertWindow.closeSystemWindow();
      // how can I send a message to te main isolate here?
    }
  }
```

**Comment by michael-ottink** [comment]
@pvsvamsi Also when I try to call a plugin from the callback like so

```
 static Future<void> systemOverlayOnClickListner(String value) async {
    if (value == 'button_app_to_foreground') {
      await SystemAlertWindow.closeSystemWindow();
      await AppAvailability.launchApp('com.company_name.app_name');
    }
  }
```

it will throw the following error

> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method launchApp on channel com.pichillilorenzo/flutter_appavailability)

Why does it do that?

**Comment by michael-ottink** [comment]
I've looked around but I don't see an isolate being spawned anywhere. I see a service being started tho. I don't really understand how the services work tho. But I openend a stackoverflow post as well.

https://stackoverflow.com/questions/62803689/missing-plugin-exception-when-calling-method-from-method-call-handler

**Comment by pvsvamsi** [comment]
Your issue is not related to isolate manager. For more info about using, the isolate manager follow this [article](https://medium.com/@lelandzach/dart-isolate-2-way-communication-89e75d973f34). Closing this issue, as it is off topic from this plugin's scope.

**Comment by pvsvamsi** [comment]
To use isolate com port data communication. Try this example

//isolate_manager.dart

`import 'dart:isolate';

import 'dart:ui';

class IsolateManager{

  static const FOREGROUND_PORT_NAME = "foreground_port";

  static SendPort lookupPortByName() {
    return IsolateNameServer.lookupPortByName(FOREGROUND_PORT_NAME);
  }

  static bool registerPortWithName(SendPort port) {
    assert(port != null, "'port' cannot be null.");
    removePortNameMapping(FOREGROUND_PORT_NAME);
    return IsolateNameServer.registerPortWithName(port, FOREGROUND_PORT_NAME);
  }

  static bool removePortNameMapping(String name) {
    assert(name != null, "'name' cannot be null.");
    return IsolateNameServer.removePortNameMapping(name);
  }

}`


//While initializing system alert window in your code

` await SystemAlertWindow.checkPermissions;
    ReceivePort _port = ReceivePort();
    IsolateManager.registerPortWithName(_port.sendPort);
    _port.listen((dynamic callBackData) {
      String tag= callBackData[0];
      switch (tag) {
        case button_app_to_foreground:
          print("Do what ever you want here. This is inside your application scope");
          break;
      }
    });
    SystemAlertWindow.registerOnClickListener(callBackFunction);`


//Callback function

bool callBackFunction(String tag) {
  print("Got tag " + tag);
  SendPort port = IsolateManager.lookupPortByName();
  port.send([tag]);
  return true;
}

**Comment by dutch-game-studio** [comment]
This works! Could you put it in the docs? I feel like a lot of people will want to use this. Also thx for the quick response and the great plugin. I think it will become populair really quick

**Comment by pvsvamsi** [comment]
Yes I have added it in the docs [here](https://github.com/pvsvamsi/SystemAlertWindow#isolate-communication)

**Comment by michael-ottink** [comment]
The example worked great. But sadly I needed it work also when the app is closed. With this example that can't be done, since the code is executed in the app score. From this comment https://github.com/flutter/flutter/issues/13937#issuecomment-656135577 I understood that plugins can be loaded with a isolate. Is there anyway I can load my plugin with the callback isolate? 

I am struggelin to try it with the FCM plugin as well like I describe here https://stackoverflow.com/questions/62820872/how-do-i-correctly-register-a-plugin-with-the-fcm-plugin but to no avail.

**Comment by asongkai** [comment]
How to close it I used both Isolate Manager and normal way but when I call 
```
await SystemAlertWindow.closeSystemWindow(); 
```
it killed my app
