### ISSUE TITLE
Is there a way with the current API to specify that the window needs to close when the app closes?

### ISSUE THREAD

**Issue by michael-ottink** [pvsvamsi/SystemAlertWindow#28]
I know I can use the WidgetsBindingObserver to close the overlay when the state of the app changes. 

But I've seen that you can specify with a service that it needs to close when the app closes. This might be more reliable? So whenever you show a overlay, you can pass a boolean if it needs to close on app close. Is this possible with the current API?

**Comment by pvsvamsi** [comment]
Why to do you want to close when the app closes? What is the use case? May be you can add forceForegroundMode through disabling background service and achieve it
