### ISSUE TITLE
Is it possible to add the FlutterNotificationClick 

### ISSUE THREAD

**Issue by michael-ottink** [pvsvamsi/SystemAlertWindow#29]
The system overlay is basically a fullscreen notification correct? Is it possible to add a FlutterNotificationClick to it?

**Comment by pvsvamsi** [comment]
@michael-ottink I Didn't understand your question. System overlay has nothing to do with notification. Click action is already available on system overlay through button click events.

**Comment by asongkai** [comment]
How to back to the app after close a button (I mean the app either it is in background or kiled) when click any button on the alert window.
