### ISSUE TITLE
SystemWindowButton onPress

### ISSUE THREAD

**Issue by Pratiknarola** [pvsvamsi/SystemAlertWindow#3]
can you please tell me how to setup onPressed event for this button?

I mean how to set logic for click on buttons. ??

**Comment by pvsvamsi** [comment]
Please follow the Readme or clone example directory and refer it

**Comment by Anon4Lulz** [comment]
@Pratiknarola 
He updated the readme and the SAW-package! Now it's even possible for me to do such Events!

Thanks @pvsvamsi !!!
