### ISSUE TITLE
Updating the plugin registry to the new api

### ISSUE THREAD

**Issue by michael-ottink** [pvsvamsi/SystemAlertWindow#30]
The device apps plugin was using legacy code for plugin registry. This plugin is also using the old way to reference the activity right? Have a look at this

https://github.com/g123k/flutter_plugin_device_apps/issues/31#issuecomment-658038702

Could this new api be implemented?

**Comment by g123k** [comment]
It is already implemented in 1.1.0

**Comment by mohamedbrahimi** [comment]
i have issues when trying to call another plugin inside the callback function of 'SystemAlertWindow.registerOnClickListener(callback);' 
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method stop on channel xyz.luan/audioplayers)
E/flutter (19952): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)

**Comment by pvsvamsi** [comment]
@michael-ottink Use the latest plugin version v1.0.0
