### ISSUE TITLE
System Alert Window will not work without enabling the android bubbles  

### ISSUE THREAD

**Issue by Maadhav** [pvsvamsi/SystemAlertWindow#32]
**I have enabled android bubbles in the notification settings but still not able to see the system alert windows in Android10+**

**To Reproduce**
Run the example app in an android R / 10+ emulator the and the error will come

**Comment by pvsvamsi** [comment]
It's currently not working on Android 11, due to tons of restrictions from google. Will soon release a fix for it

**Comment by pvsvamsi** [comment]
It's fixed now in 0.4.0
