### ISSUE TITLE
Open the app automatically when someone instagram or some other applications

### ISSUE THREAD

**Issue by nicks258** [pvsvamsi/SystemAlertWindow#33]
@pvsvamsi Really appreciate your works and it is working smoothly. But i am exited to know that is possible to open my alert window or overlay window whenever someone opens any specific application. Thanks for your time.

**Comment by bnair2001** [comment]
Hi, were you able to find a solution? Looking for the same

**Comment by pvsvamsi** [comment]
That is beyond the scope of this project
