### ISSUE TITLE
I cant change the callback status from out side.

### ISSUE THREAD

**Issue by the6nnoo** [pvsvamsi/SystemAlertWindow#36]
For example，these is my code
![image](https://user-images.githubusercontent.com/13672968/95651389-a8910c00-0b1c-11eb-9773-0f5431d6b029.png)
I cant change the “isStarting” from out side。
it is very queer。
if i close the window and reCreate it.
i cant init the status. or it is not working.
pls tell me how to do it

**Comment by pvsvamsi** [comment]
Because it's running in the background isolate

read this
https://github.com/pvsvamsi/SystemAlertWindow#isolate-communication
