### ISSUE TITLE
Keyboard interaction is not possible in the window below the overlay.

### ISSUE THREAD

**Issue by taej0127** [pvsvamsi/SystemAlertWindow#4]
In android 9

**Comment by pvsvamsi** [comment]
Please clarify the issue with the below details,

Version of SystemAlertWindow :
Screenshot of the issue:
Expected Behavior:
Code Snippet of the SystemAlertWindow invocation:

**Comment by taej0127** [comment]
thank you for your reply.

- **Version of SystemAlertWindow** : 0.1.5+1 / 0.2.1
 
- **Screenshot of the issue**:
 ![Screenshot_1582946003](https://user-images.githubusercontent.com/16468579/75599942-f0fb3c80-5aec-11ea-9094-b6f96e3cde99.png)
 
- **Expected Behavior**:  the virtual keyboard should appear when I click on the form in the overlaid window. Besides form, other keyboard interactions are expected to be difficult.
 
- **Code Snippet of the SystemAlertWindow invocation**: test with example code

**Comment by merlinko637** [comment]
@pvsvamsi I have the same problem :/ is it possible to somehow fix it?

**Comment by pvsvamsi** [comment]
@taej0127 @merlinko637 Fixed this issue in v0.2.2+1

**Comment by taej0127** [comment]
I really appreciate your effort ☺️
