### ISSUE TITLE
closeSystemWindow is not working properly

### ISSUE THREAD

**Issue by cangSDARM** [pvsvamsi/SystemAlertWindow#40]
When I try to call `closeSystemWindow` as an example, It will print some errors:

```
[ xx ms ] D/skia     (18240): Shader compilation error
[       ] D/skia     (18240): ---------------------------
[       ] D/skia     (18240): Errors:
[       ] D/skia     (18240):
```

and the window was not closed, even if those states ware changed.

On: Android9 AOSP emulator with Flutter 1.22.3

**Comment by pvsvamsi** [comment]
What is the plugin version?
Can you elaborate your issue more with the code snippet?
Test run the example and share the result

**Comment by cangSDARM** [comment]
Thx, I solved this issue. Turns out I used a component which does not belong to SystemWindow
