### ISSUE TITLE
FloatingActionButton

### ISSUE THREAD

**Issue by imeDevelopers** [pvsvamsi/SystemAlertWindow#42]
https://www.journaldev.com/14673/android-floating-widget

it's the main reason of the overlay widgets .., so it's the most important one, more than the truecaller window ..
we need this widget with very simple action ..
when we press on it just bring the app in foreground ..

i can't do this ..

and why you force the windows background color to white ?
i want to control it and change it's color to transparent for example or black ..

and there's another problem .. if you make small size window , when you move it any direction , it automatically go back to the right side ..

please fix this things ,thx.

**Comment by nsumithradeveloper** [comment]
Yes. Adding to that bringing the app foreground with a specific screen would be more useful. Please add the features. Thanks

**Comment by pvsvamsi** [comment]
@imeDevelopers This plugin is intended for a different usage than overlay widgets.
Starting from android 11, it shows a floating button kind of notification. On click of it, the actual notification will be displayed (like fb chat).
Android 10 and below, it shows the overlay window.
There are multiple parameters already available to change the color of the overlay window.

**Comment by niltondiniz** [comment]
> @imeDevelopers This plugin is intended for a different usage than overlay widgets.
> Starting from android 11, it shows a floating button kind of notification. On click of it, the actual notification will be displayed (like fb chat).
> Android 10 and below, it shows the overlay window.
> There are multiple parameters already available to change the color of the overlay window.




> https://www.journaldev.com/14673/android-floating-widget
> 
> it's the main reason of the overlay widgets .., so it's the most important one, more than the truecaller window ..
> we need this widget with very simple action ..
> when we press on it just bring the app in foreground ..
> 
> i can't do this ..
> 
> and why you force the windows background color to white ?
> i want to control it and change it's color to transparent for example or black ..
> 
> and there's another problem .. if you make small size window , when you move it any direction , it automatically go back to the right side ..
> 
> please fix this things ,thx.

Hey!
There is a package that I created that can help you with the floating action button.

https://pub.dev/packages/float_button_overlay

**Comment by pvsvamsi** [comment]
@imeDevelopers Use version v1.2.0 to change the background color & disable clicks across the system window
