### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by c1avie** [pvsvamsi/SystemAlertWindow#47]
error message:

![image](https://user-images.githubusercontent.com/2912208/111444265-25b45300-8745-11eb-8247-efff8a0bbb56.png)

flutter doctor:

![image](https://user-images.githubusercontent.com/2912208/111444320-35cc3280-8745-11eb-8526-caf8e72c1fcb.png)

**Comment by pvsvamsi** [comment]
What is your SDK and XCode version?
