### ISSUE TITLE
Callback params

### ISSUE THREAD

**Issue by niltondiniz** [pvsvamsi/SystemAlertWindow#52]
Hi!

It's possible to send params to callback function?

my Callback function:

void callBack(String tag) async {  

 swicth(tag){
    case "footer_button":
        registerCallBack(trip, tag);
}

 "I need a param here --> trip. I've tried to pass by global variable, but i got only null value"

**Comment by pvsvamsi** [comment]
Call back function is to notify which button is clicked based on it's tags. So callBack function doesn't support custom parameters. Instead of passing global variable, try to use isolate communication for accessing data in main isolate from your callback isolate
