### ISSUE TITLE
How to install probably -getting  error: cannot find symbol String prefMode = (String) arguments.get(3); on Run

### ISSUE THREAD

**Issue by Mr-Slimon** [pvsvamsi/SystemAlertWindow#54]
When ever i run application 
i get this error :

`

When ever i run application 
i get this error :

`
Launching lib\main.dart on M2007J20CG in debug mode...
Parameter format not correct -
C:\flutter\.pub-cache\hosted\pub.dartlang.org\system_alert_window-0.4.3\android\src\main\java\in\jvapps\system_alert_window\SystemAlertWindowPlugin.java:137: error: cannot find symbol
                    String prefMode = (String) arguments.get(3);
                                               ^
  symbol:   variable arguments
  location: class SystemAlertWindowPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\system_alert_window-0.4.3\android\src\main\java\in\jvapps\system_alert_window\SystemAlertWindowPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':system_alert_window:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

`

am I doing something wrong ?

**Comment by Mr-Slimon** [comment]
Sorry to bother - this error occur if the id is very large - tried smaller id and it fixed the problem

**Comment by indrakumarprajapat** [comment]
Same for me, 
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Launching lib/main.dart on moto g 8 plus in debug mode...
Running Gradle task 'assembleDebug'...
/Users/indras/Github/SystemAlertWindow/android/src/main/java/in/jvapps/system_alert_window/SystemAlertWindowPlugin.java:137: error: cannot find symbol
                    String prefMode = (String) arguments.get(3);
                                               ^
  symbol:   variable arguments
  location: class SystemAlertWindowPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/indras/Github/SystemAlertWindow/android/src/main/java/in/jvapps/system_alert_window/SystemAlertWindowPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':system_alert_window:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by indrakumarprajapat** [comment]
Its Working, followed the changes mentioned in PR #53

**Comment by Mr-Slimon** [comment]
well this error is gone - now I am getting this error 
Application.java:18: error: incompatible types: PluginRegistry cannot be converted to FlutterEngine
          GeneratedPluginRegistrant.registerWith(pluginRegistry);

how I fixed it,  is by changing Application.java

first I imported this in the beginning of file after the package name :

`import io.flutter.embedding.engine.FlutterEngine;   `


Next I changed the last function from this 

 ```
 @Override
    public void registerWith(PluginRegistry pluginRegistry) {
        GeneratedPluginRegistrant.registerWith(pluginRegistry);
    }
```
Into this :

```
@Override
    public void registerWith(PluginRegistry pluginRegistry) {
        GeneratedPluginRegistrant.registerWith((FlutterEngine)pluginRegistry);
    }
```

I don't know if this should be pushed also to the master  or not - so I will leave it here in case someone need it.

Now it is building but the app is not launching - I get error that Main Activity class is not found , so I removed all the application.java files and instead used the Kotlin code from homepage  only
