### ISSUE TITLE
Sound and Vibration support

### ISSUE THREAD

**Issue by Mr-Slimon** [pvsvamsi/SystemAlertWindow#55]
Is it possible to support playing the ringtone sound + Vibrating 

like incoming call Notification ?

I don't ask for custom Sound or vibration - just the device default one 

and if it possible can you tell us how 

Thanks in advance for this great library :)

**Comment by pvsvamsi** [comment]
That's outside the scope of this package. You can add your custom logics in the call backs/while invoking the overlay
