### ISSUE TITLE
Redirect to flutter screen

### ISSUE THREAD

**Issue by Mr-Slimon** [pvsvamsi/SystemAlertWindow#56]
How can I Open Flutter app and redirect to certain screen after pressing any of the buttons ?

I don't know how to implement this in java 

but I know it is possible as it had been made before in this package

maybe it could help

https://github.com/ConnectyCube/connectycube-flutter-call-kit

**Comment by pvsvamsi** [comment]
That's beyond the scope of this package. You have to handle the logic in the callbacks.
