### ISSUE TITLE
Allow footer buttons to be arranged in a column

### ISSUE THREAD

**Issue by TylerMutai** [pvsvamsi/SystemAlertWindow#58]
At the moment, when you stack footer buttons, they are arranged in a row. Also, there is no way of appending buttons to the System Alert Window. 

It would be great if we could arrange the footer buttons in a column. Alternatively, you could include the buttons in the body element of the system alert window and allow us to arrange them in a column or row.

**Comment by pvsvamsi** [comment]
It's supported in the latest release v2.0.0
