### ISSUE TITLE
How to Open app on button click in SystemOverlayWindow?

### ISSUE THREAD

**Issue by AmSn6** [pvsvamsi/SystemAlertWindow#6]
I have successfully implemented the overlay alert. But I want to open the app when user clicks on the button in the overlay alert... Thank you...

**Comment by pvsvamsi** [comment]
That is beyond the scope of this library. Use Url Launcher for that.

**Comment by devsarfo** [comment]
Hi @pvsvamsi, I successfully used your plugin to open app on Button Click. Since you can use the IsolateManager to listen to the actions on the main thread, you can open app from the main thread and it works. But in my case the app wasn't finished. On back press, it was minimised to background.

Thanks for the wonderful plugin!

**Comment by archie20** [comment]
> Hi @pvsvamsi, I successfully used your plugin to open app on Button Click. Since you can use the IsolateManager to listen to the actions on the main thread, you can open app from the main thread and it works. But in my case the app wasn't finished. On back press, it was minimised to background.
> 
> Thanks for the wonderful plugin!

How were you able to open the app

**Comment by devsarfo** [comment]
> > Hi @pvsvamsi, I successfully used your plugin to open app on Button Click. Since you can use the IsolateManager to listen to the actions on the main thread, you can open app from the main thread and it works. But in my case the app wasn't finished. On back press, it was minimised to background.
> > Thanks for the wonderful plugin!
> 
> How were you able to open the app


I used another flutter plugin: bringtoforeground. You can find it here: https://pub.dev/packages/bringtoforeground

Once I call this **Bringtoforeground.bringAppToForeground();** in the IsolateManager's port listen event.
