### ISSUE TITLE
this error appear when try to run my app

### ISSUE THREAD

**Issue by mostafasaadamin** [pvsvamsi/SystemAlertWindow#61]
`C:\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\system_alert_window-0.4.3\android\src\main\java\in\jvapps\system_alert_window\SystemAlertWindowPlugin.java:137: error: cannot find symbol
                    String prefMode = (String) arguments.get(3);`

**Comment by pvsvamsi** [comment]
Use system_alert_window: 0.4.2+2
