### ISSUE TITLE
Not asking for permission of Bubble or AppearOnTop in Android 11

### ISSUE THREAD

**Issue by Anas-jed** [pvsvamsi/SystemAlertWindow#64]
I have implemented the code but running below Android 10 displays overlay and ask for permission. The problem is on Android 11 where it does not ask for the permission of both AppearOnTop And Bubble permission. Also checked with `SystemWindowPrefMode.BUBBLE` or `SystemWindowPrefMode.DEFAULT` 

i Have to manually open the settings and allow to display it.

**Comment by shivaburade** [comment]
You can use permission_handler package and ask permission before using it. I have made a sample application that requests for permission before using bubble/AppearOnTop. 

Clone this repo and you will be able to use it. 
https://github.com/shivaburade/overlay_test_with_permission/blob/master/lib/main.dart#L53

**Comment by pvsvamsi** [comment]
@Anas-jed Use the latest plugin version v1.0.0
