### ISSUE TITLE
Not working on Xiaomi phones

### ISSUE THREAD

**Issue by lionuncle** [pvsvamsi/SystemAlertWindow#65]
**Describe the bug**
The plugin doesn't work on Xiaomi devices, you have to explicitly go to setting and grant "Display pop-up windows while running in the background" to make it work!

**Versions:**
 - SystemAlertWindow: 0.5.0
 - Device: any xiaomi device
 - OS: Android 10

**Comment by shivaburade** [comment]
You can use permission_handler package and ask permission before using it. I have made a sample application that requests for permission before using bubble/AppearOnTop.

Clone this repo and you will be able to use it.
https://github.com/shivaburade/overlay_test_with_permission/blob/master/lib/main.dart#L53

**Comment by pvsvamsi** [comment]
@lionuncle Unfortunately there is no work around for that, as it's a restriction from Xiaomi.
