### ISSUE TITLE
closeSystemWindow is not working properly

### ISSUE THREAD

**Issue by josefrvaldes** [pvsvamsi/SystemAlertWindow#67]
After calling showSystemWindow in android 11, with prefMode=SystemWindowPrefMode.OVERLAY, it displays correctly the expected screen, but after clicking a button to close the screen and calling closeSystemWindow, the window doesn't close.
And I'm getting this message from the console: `[        ] I/SystemAlertWindowPlugin( 6688): Invoke call back success`, so it's supposed to be working fine, but it doesn't.

This system window even remains in front of my screen and I can't get rid of it, it's displaying always and I have to restart my phone in order for it to dissapear.

I'm using version 0.4.3 of SystemAlertWindow and android 11. I'm not testing it in iOS because this app is only for android.

This is the code I'm using to show the alert window:

`return await SystemAlertWindow.showSystemWindow(
        header: SystemWindowHeader(...),
        body: SystemWindowBody(...),
        footer: SystemWindowFooter(...),
        width: 400,
        prefMode: SystemWindowPrefMode.OVERLAY,
        margin: SystemWindowMargin(left: 0, right: 0, top: 0, bottom: 0),
        gravity: SystemWindowGravity.CENTER);`

And this is the code I'm using to try to close the alert window:
`SystemAlertWindow.closeSystemWindow();`

**Comment by pvsvamsi** [comment]
Are you receiving the button click event in your code?

**Comment by josefrvaldes** [comment]
Yes I am. The problem is not related to that button event. The problem is related to SystemAlertWindow.closeSystemWindow() not working.

**Comment by josefrvaldes** [comment]
Something new here? Do you have any idea of what can be happening? 
Thanks!

**Comment by dcdj99** [comment]
i'm having the exact same issue as well

**Comment by dcdj99** [comment]
im using package version 0.4.3+1

 Flutter version 2.4.0-0.0

 Dart version 2.14.0 (build 2.14.0-258.0.dev)

**Comment by dcdj99** [comment]
Hey i've found the issue, 

in android > src.main > system_alert_window > systemAlertWindowPlugin > line 165 > remove  the second condition in if statement  " || Build.VERSION.SDK_INT > Build.VERSION_CODES.Q "

**Comment by josefrvaldes** [comment]
@pvsvamsi could you please fix this issue with the solution that @dcdj99 has provided?

**Comment by pvsvamsi** [comment]
@josefrvaldes @dcdj99 Use the latest plugin version v1.0.0

**Comment by dcdj99** [comment]
There is still a problem with this in the new version
