### ISSUE TITLE
Null safety error messages

### ISSUE THREAD

**Issue by pulstar** [pvsvamsi/SystemAlertWindow#69]
**Describe the bug**
SystemAlertWindow is showing the following error messages while compiling:

>../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/system_alert_window->0.5.0+1/lib/models/system_window_body.dart:19:49: Warning: Operand of null-aware operation '?.' has type 'EachRow' which excludes null.
> - 'EachRow' is from 'package:system_alert_window/models/system_window_body.dart' ('../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/system_alert_window-0.5.0+1/lib/models/system_window_body.dart').
>          : List<dynamic>.from(rows!.map((x) => x?.getMap())),
>                                                ^
>../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/system_alert_window-0.5.0+1/lib/models/system_window_body.dart:41:52: Warning: Operand of null-aware operation '?.' has type 'EachColumn' which excludes null.
> - 'EachColumn' is from 'package:system_alert_window/models/system_window_body.dart' ('../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/system_alert_window-0.5.0+1/lib/models/system_window_body.dart').
>          : List<dynamic>.from(columns!.map((x) => x?.getMap())),

**Versions (please complete the following information):**
 - SystemAlertWindow: ^0.5.0+1
 - Device: Blu Vivo XI
 - OS: Android 9.0

**Additional context**
```
environment:
  sdk: ">=2.11.0 <3.0.0"
```

**flutter doctor**
>Doctor summary (to see all details, run flutter doctor -v):
>[√] Flutter (Channel stable, **2.2.3**, on Microsoft Windows [version 10.0.19042.1165], locale pt-BR)
>[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>[√] Chrome - develop for the web
>[√] Android Studio (version 4.1.0)
>[√] Connected device (4 available)

**Comment by pvsvamsi** [comment]
@pulstar Use the latest plugin version v1.0.0
