### ISSUE TITLE
NullPointerException when trying to show bubble notification on android 11

### ISSUE THREAD

**Issue by josefrvaldes** [pvsvamsi/SystemAlertWindow#70]
**Describe the bug**
I'm getting this error:

`AndroidRuntime( 6706): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.icabbi.paratransit/in.jvapps.system_alert_window.BubbleActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6706): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime( 6706): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime( 6706): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime( 6706): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6706): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6706): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 6706): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6706): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6706): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6706): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 6706): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6706): 	at in.jvapps.system_alert_window.views.BodyView.getView(BodyView.java:38)
E/AndroidRuntime( 6706): 	at in.jvapps.system_alert_window.BubbleActivity.configureUI(BubbleActivity.java:52)
E/AndroidRuntime( 6706): 	at in.jvapps.system_alert_window.BubbleActivity.onCreate(BubbleActivity.java:43)
E/AndroidRuntime( 6706): 	at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime( 6706): 	at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime( 6706): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime( 6706): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime( 6706): 	... 11 more`

**To Reproduce**
just calling this code:

`
static Future<void> showMessage(String title, String msg) async {
    final hasPermission = await SystemAlertWindow.checkPermissions();
    if (hasPermission == false) {
      await SystemAlertWindow.requestPermissions();
    }
    await SystemAlertWindow.registerOnClickListener(callBackFunction);

    final bgColor = Colors.grey[100];

    SystemWindowHeader header = SystemWindowHeader(...);

    SystemWindowFooter footer = SystemWindowFooter(...);

    return await SystemAlertWindow.showSystemWindow(
        header: header,
        footer: footer,
        width: 400,
        prefMode: SystemWindowPrefMode.DEFAULT,
        margin: SystemWindowMargin(left: 0, right: 0, top: 0, bottom: 0),
        gravity: SystemWindowGravity.CENTER);
  }
}

`

**Expected behavior**
it shouldn't fail

**Versions (please complete the following information):**
 - SystemAlertWindow: 0.4.4
 - Device: emulator
 - OS: android 11

**Additional context**
All permissions are correctly given. The notification itself shows the bubble, but instantly it crashes. It just crashes.
The "all conversations can bubble" is activated too.

**Comment by josefrvaldes** [comment]
The error keeps happening. Something new here?

**Comment by pvsvamsi** [comment]
@josefrvaldes Use the latest plugin version v1.0.0

**Comment by Dhirajraje** [comment]
Error persists
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
       at in.jvapps.system_alert_window.e.b.a(:26)
       at in.jvapps.system_alert_window.BubbleActivity.onCreate(:1)
       at android.app.Activity.performCreate(Activity.java:8006)
       at android.app.Activity.performCreate(Activity.java:7990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
