### ISSUE TITLE
The plugin `system_alert_window` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by esther-86** [pvsvamsi/SystemAlertWindow#72]
**Describe the bug**
After get dependencies, I saw this warning in the console:
The plugin `system_alert_window` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**To Reproduce**
1. system_alert_window: ^0.5.0+1 in pubspec.yaml and click get dependencies

**Expected behavior**
Please see if the plugin supports the Android V2. It would be good if the warning is removed.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - SystemAlertWindow: ^0.5.0+1
 - Device: Nexus 9 API 8 in emulator
 - OS: Windows 10 64-bit

**Additional context**
N/A

**Comment by pvsvamsi** [comment]
@esther-86 Use the latest plugin version v1.0.0
