### ISSUE TITLE
Nothing happens when running on iOS emulator

### ISSUE THREAD

**Issue by Leo-Strijbos** [pvsvamsi/SystemAlertWindow#73]
Hi Pvsvamsi,
I love the plugin, its really cool!

I've been trying to run it on iOS and clicking the button does nothing. It works perfectly on android. 

Steps to reproduce: download and run the example project. 

Is it supposed to work on iOS?
Thanks in advance

**Comment by pvsvamsi** [comment]
This plugin doesn't support iOS as of now.
