### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jayachandra572** [pvsvamsi/SystemAlertWindow#75]
**Describe the bug**

**To Reproduce**
![Screenshot from 2021-11-11 10-10-50](https://user-images.githubusercontent.com/59283888/141238347-e871c728-e780-4f20-afd1-6940702c6343.png)

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - SystemAlertWindow: [eg. 0.2.1]

**Additional context**

**Comment by pvsvamsi** [comment]
@jayachandra572 Use the latest plugin version v1.0.0
