### ISSUE TITLE
Android 12 not working

### ISSUE THREAD

**Issue by sunny5497** [pvsvamsi/SystemAlertWindow#77]
Overlay not showing in android 12

No overlay shown in A12 currently.

Error Log
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#in.jvapps.system_alert_window(27257): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/MethodChannel#in.jvapps.system_alert_window(27257): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
E/MethodChannel#in.jvapps.system_alert_window(27257): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
E/MethodChannel#in.jvapps.system_alert_window(27257): 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
E/MethodChannel#in.jvapps.system_alert_window(27257): 	at in.jvapps.system_alert_window.utils.NotificationHelper.showNotification(NotificationHelper.java:136)

Version android 12

**Comment by pvsvamsi** [comment]
@sunny5497 I have tested the version 1.0.0 on Android 12 (API 32). There was no runtime exception. 
Also your error log is more related to work run time dependency, which is not used in this package. https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a

**Comment by EngMahmoudMagdy** [comment]
Hi, 
I've tried to use the library with my application with 
```

flutter.targetSdkVersion=31
flutter.compileSdkVersion=31
```

But, what happened is after adding the proper code in the docs, the application throwing the exception that in the link and can't be handled from Flutter side to show system window
here is the exception

`
E/SAW:Plugin(14292): java.lang.IllegalArgumentException: {appPackage}: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/SAW:Plugin(14292): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

I don't know it already solved on some other versions or not but the latest versions is not working

**Comment by GiddyNaya** [comment]
Error lines in context:
in.jvapps.system_alert_window.utils.NotificationHelper.showNotification(NotificationHelper.java:136)
in.jvapps.system_alert_window.utils.NotificationHelper.showNotification(NotificationHelper.java:148)

Class in context:
NotificationHelper.java

Fix:
Replace all "`PendingIntent.FLAG_UPDATE_CURRENT`" inside class to:

`Build.VERSION.SDK_INT >= Build.VERSION_CODES.M ? (PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_MUTABLE) : PendingIntent.FLAG_UPDATE_CURRENT`

**Comment by pvsvamsi** [comment]
@sunny5497 @EngMahmoudMagdy Please use the version 1.1.1

**Comment by EngMahmoudMagdy** [comment]
I found the solution that I have to use 
`prefMode = SystemWindowPrefMode.DEFAULT`
and by default it will work on it and choose the proper way for each Android version if it will be bubble or Alert
Thanks for help, guys
