### ISSUE TITLE
i think this package depends on floaty_head package which is old

### ISSUE THREAD

**Issue by Plantake** [pvsvamsi/SystemAlertWindow#78]
its showing this error

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\floaty_head-2.0.0-nullsafety.0\android\src\main\kotlin\ni\devotion\floaty_head\FloatyHeadPlugin.kt: (280, 52): Unresolved reference: getInstance

**Comment by pvsvamsi** [comment]
No it doesn't. There are no dependencies for this package.
