### ISSUE TITLE
setPluginRegistrant method pops an error

### ISSUE THREAD

**Issue by Dreezyagu** [pvsvamsi/SystemAlertWindow#79]
When you copy and paste the Kotlin code meant in the Application.kt from the Readme on pub.dev, the code " SystemAlertWindowPlugin.setPluginRegistrant(this)" gives an unresolved reference error.
 
<img width="908" alt="Screenshot 2021-12-18 at 18 26 58" src="https://user-images.githubusercontent.com/58152759/146650258-20cabd39-66e0-4617-8bf3-beea4f65da0c.png">

**Comment by pvsvamsi** [comment]
Application.kt is no more used in the latest version. You can remove that file

**Comment by Manishmg3994** [comment]
are you sure that we can delete that file then what to do for androidmanifiest.xml
