### ISSUE TITLE
Unable to access static members of classes in callback function

### ISSUE THREAD

**Issue by merlinko637** [pvsvamsi/SystemAlertWindow#8]
Hello, I have a following problem. In callback function I need to access another classes static object, but the problem is, as soon as it gets to the callback function, the object seems to be null. I really need this, to access singleton instance and execute some methods, but after almost 2 days I am still unable to do this. Here is a simple example of what I am trying to achieve (it is your example modified):

```
class TestClass {
  static TestModel myStaticModel;

  static void fillModel(){
    myStaticModel = new TestModel("John doe", 5);
  }
}

class TestModel {
  String name;
  int age;

  TestModel(this.name, this.age);
}

void callBack(String tag) {
  switch(tag){
    case "myButton":
      print(TestClass.myStaticModel);   //this prints null
      break;
    default:
      print("OnClick event of $tag");
  }
}
```

TestClass.fillModel() is called when invoking showOverlayWindow()

Any help will be appriciated

**Comment by pvsvamsi** [comment]
Callbacks are executed in isolates. You have to use [https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html](IsolateNameServer ) to communicate between main thread and the isolate
