### ISSUE TITLE
issues with closing in overlay mode (related with #67)

### ISSUE THREAD

**Issue by dcdj99** [pvsvamsi/SystemAlertWindow#80]
related with #67 @pvsvamsi 

After upgrading to the latest version, there is still an issue closing the window in overlay mode.

The bug can be traced back to SystemAlertWindowPlugin.java under case 'closeSystemWindow' at line 240.

I think the wrong method for closure is being used, the one for bubble mode is called instead of for the overlay mode.

**Comment by pvsvamsi** [comment]
@dcdj99 Share the screenshot of the error you are facing and the plugin version you are using.

Line 240 in SystemAlertWindowPlugin.java has completely different functionality
![image](https://user-images.githubusercontent.com/20770470/147905992-d753f1f4-a8ad-479d-bda1-4cbfeffb90ed.png)
