### ISSUE TITLE
Make a video tutorial about how to use this package 

### ISSUE THREAD

**Issue by Plantake** [pvsvamsi/SystemAlertWindow#86]
it really gets confusing sometimes

**Comment by pvsvamsi** [comment]
Please follow the example / documentation to understand the flow. For any specific question, you can ask it here

**Comment by Plantake** [comment]
i did but it didn’t work. can you give a proper documentation. In previous versions i had to make a application.kt but in newer versions I dont have to things are getting real confusing for a beginner like me

**Comment by pvsvamsi** [comment]
@Plantake That's because of new changes in Flutter 2.x. You can read about it here in detail.
[https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
