### ISSUE TITLE
can we overlay icon of the app on other apps .

### ISSUE THREAD

**Issue by exarcplus** [pvsvamsi/SystemAlertWindow#88]
am developing an app in flutter . that require google navigation , when my app redirects to google map I have to show my app icon on top of the map . when user clicks on app icon it should redirect my app again

**Comment by X-SLAYER** [comment]
check out this package it will help you to put flutter widgets in your overlay [flutter_overlay_window](https://pub.dev/packages/flutter_overlay_window) so I think it will fit your requirements

**Comment by pvsvamsi** [comment]
It's supported in the latest release v2.0.0
