### ISSUE TITLE
Popup window from backend

### ISSUE THREAD

**Issue by muhamadkhuram** [pvsvamsi/SystemAlertWindow#89]
I want to popup a widget from the backend which will be irrespective of time or any schedule.

Just like we push notifications from the backend it will be very good to have this feature to popup a widget with specific data any time.

**Comment by pvsvamsi** [comment]
This plugin works from background isolate as well. So you need to invoke the plugin methods from your backend logic.

**Comment by anand-seeroo** [comment]
could you please explain.
