### ISSUE TITLE
Chat Head Like Floating overlay bubble

### ISSUE THREAD

**Issue by mjafartp** [pvsvamsi/SystemAlertWindow#9]
Need messenger chat head like floating action button and close on drop to bottom feature.

**Comment by pvsvamsi** [comment]
Bubble functionality is available for Android 11 and above. For android 10 and below, it continues to show overlay window, as Bubble functionality is disabled by default on android 10 devices and can only be enabled from developer options.

**Comment by mjafartp** [comment]
need to show overlay window in round bubble shape
