### ISSUE TITLE
I don't want to put the control on top of all applications. I want to put it under all applications, which is equivalent to all the lowest mobile desktop. Is this feature provided? What should I do?

### ISSUE THREAD

**Issue by gateshibill** [pvsvamsi/SystemAlertWindow#90]
I don't want to put the control on top of all applications. I want to put it under all applications, which is equivalent to all the lowest mobile desktop. Is this feature provided? What should I do?

**Comment by pvsvamsi** [comment]
This is outside the scope and definition of this package
