### ISSUE TITLE
'system_alert_window/system_alert_window-Swift.h' file not found    

### ISSUE THREAD

**Issue by shalini-kad** [pvsvamsi/SystemAlertWindow#92]
Hi, 
I get this error on ios while trying to run the project. 

**Lexical or Preprocessor Issue Group :**
/development/flutter/.pub-cache/hosted/pub.dartlang.org/system_alert_window-1.1.1/ios/Classes/SystemAlertWindowPlugin.m:2:9: 'system_alert_window/system_alert_window-Swift.h' file not found

 Please help me out with solving this issue

**Comment by pvsvamsi** [comment]
This plugin doesn't support iOS
