### ISSUE TITLE
Is there any way to display system window in background thread ?

### ISSUE THREAD

**Issue by shaunhossain** [pvsvamsi/SystemAlertWindow#93]
i am using system alert manager to display alarm notification . the feature is work fine with my application open and also work in foreground thread . i faced issue only when the app is close . i implement the method on  alarm manager isolate function , so that it call be call on background

**Comment by pvsvamsi** [comment]
You can directly invoke this plugin in isolate.  Refer to this [Isolate Communication](https://github.com/pvsvamsi/SystemAlertWindow#isolate-communication)
