### ISSUE TITLE
Add option for transparent background (click-through)

### ISSUE THREAD

**Issue by razfazz** [pvsvamsi/SystemAlertWindow#94]
It would be nice if there would be an option to make the background transparent and not consuming tap events. 
that would allow us to show for example only a shape.

Btw. Thank you for that great package

**Comment by fewling** [comment]
As of version 1.1.2, I made the background transparent by directly modifing the package file (just one line).

Look into your flutter sdk directory and find the file:
`flutter\.pub-cache\hosted\pub.dartlang.org\system_alert_window-1.1.2\android\src\main\java\in\jvapps\system_alert_window\services\WindowServiceNew.java`.

You should be able to find a function, `private void setWindowView(...)`, and remove/comment the line `windowView.setBackgroundColor(Color.WHITE);`.

Then in flutter, header, body and/or footer widget(s) should contains a `decoration` property where you can set the background transparent as well.
