### ISSUE TITLE
How to change notification Icon and Title

### ISSUE THREAD

**Issue by zogol** [pvsvamsi/SystemAlertWindow#96]
I tried to change the default "Overlay window service is running" by setting the properties "notificationTitle" and "notificationBody" inside the SystemAlertWindow.showSystemWindow method. but the notification still shows  "Overlay window service is running"

**Comment by pvsvamsi** [comment]
Currently notificationTitle and notificationBody are supported only for bubbles. Wait for next release to support it in overlay window as well
