### ISSUE TITLE
Bug when compiling the example code ?

### ISSUE THREAD

**Issue by TheauLep** [pvsvamsi/SystemAlertWindow#97]
Got this error and can't test the example, does anyone have the same issue or is able to help me ? Thanks in advance :) 

e: /.../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-3.1.0/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt: (34, 24): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Git-GA** [comment]
share_plus is obsolete. Remove it from dependencies and add it again via flutter pub add.
