### ISSUE TITLE
not working on release mode 

### ISSUE THREAD

**Issue by YaniSourceOne** [pvsvamsi/SystemAlertWindow#99]
**Describe the bug**
application works good on debug mode but does not on release when attempting to click a button (callback function)

I got this error  
`E/flutter (27261): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:system_alert_window/system_alert_window.dart' not found.
E/flutter (27261): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (27261): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter (27261): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (27261): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.`

**Comment by pvsvamsi** [comment]
Use the latest version v1.2.1
